# Generated by Django 3.2.15 on 2022-09-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwoed',
            new_name='password',
        ),
    ]
